# Generated by Django 4.2.20 on 2025-05-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='api_user_id',
        ),
        migrations.AddField(
            model_name='student',
            name='api_user_hash',
            field=models.CharField(blank=True, help_text="Tashqi API dagi foydalanuvchi uchun unikal hash (agar mavjud bo'lsa)", max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id_number',
            field=models.CharField(blank=True, help_text='API dan olingan talabaning ID raqami', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(help_text='Tizimga kirish uchun foydalaniladigan login (odatda Talaba ID raqami)', max_length=150, unique=True),
        ),
    ]
