# Generated by Django 4.2.20 on 2025-05-28 11:04

import auth_app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_app', '0003_alter_student_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsiblePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ismi')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiyasi')),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True, verbose_name='Otasining ismi (ixtiyoriy)')),
                ('position', models.CharField(help_text='Masalan, Dekan muovini, Tyutor, Kafedra mudiri', max_length=255, verbose_name='Lavozimi')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Elektron pochta')),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefon raqami')),
                ('office_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Xonasi / Joylashuvi')),
                ('responsibilities_short', models.TextField(blank=True, help_text='Talabalar qanday masalalarda murojaat qilishi mumkinligi haqida.', null=True, verbose_name="Mas'uliyat sohalari (qisqacha)")),
                ('is_active', models.BooleanField(default=True, help_text="Aktiv bo'lmagan shaxslar talabalarga ko'rinmaydi.", verbose_name='Aktivmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Mas'ul shaxs",
                'verbose_name_plural': "Mas'ul shaxslar",
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name="So'rovnoma nomi")),
                ('purpose', models.TextField(blank=True, null=True, verbose_name="So'rovnoma maqsadi")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mazmuni / Tavsifi')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateTimeField(blank=True, help_text="Agar bo'sh qoldirilsa, so'rovnoma muddatsiz bo'ladi.", null=True, verbose_name='Tugash sanasi')),
                ('is_active', models.BooleanField(default=True, help_text="Aktiv bo'lmagan so'rovnomalar talabalarga ko'rinmaydi.", verbose_name='Aktivmi?')),
                ('is_anonymous', models.BooleanField(default=False, help_text="Agar anonim bo'lsa, talaba shaxsi javoblarga bog'lanmaydi.", verbose_name='Anonimmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_surveys', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi (Admin)')),
            ],
            options={
                'verbose_name': "So'rovnoma",
                'verbose_name_plural': "So'rovnomalar",
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-updated_at', 'last_name', 'first_name'], 'verbose_name': 'Talaba (API)', 'verbose_name_plural': 'Talabalar (API)'},
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqti')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to='auth_app.student', verbose_name='Talaba')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='auth_app.survey', verbose_name="So'rovnoma")),
            ],
            options={
                'verbose_name': "So'rovnoma javobi (Ishtirok)",
                'verbose_name_plural': "So'rovnoma javoblari (Ishtiroklar)",
                'ordering': ['-submitted_at'],
                'unique_together': {('survey', 'student')},
            },
        ),
        migrations.CreateModel(
            name='SurveyFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=auth_app.models.survey_file_upload_path, verbose_name='Fayl/Rasm')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='Izoh (ixtiyoriy)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='auth_app.survey', verbose_name="So'rovnoma")),
            ],
            options={
                'verbose_name': "So'rovnoma fayli",
                'verbose_name_plural': "So'rovnoma fayllari",
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Savol matni')),
                ('question_type', models.CharField(choices=[('text', 'Matnli javob'), ('single_choice', 'Yagona tanlov'), ('multiple_choice', "Ko'p tanlov")], default='text', max_length=20, verbose_name='Savol turi')),
                ('order', models.PositiveIntegerField(default=0, help_text="Savollarni ko'rsatish tartibi.", verbose_name='Tartib raqami')),
                ('is_required', models.BooleanField(default=True, verbose_name='Majburiymi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='auth_app.survey', verbose_name="So'rovnoma")),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
                'ordering': ['survey', 'order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageToResponsible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Xabar mavzusi')),
                ('content', models.TextField(verbose_name='Xabar mazmuni')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('seen', "Ko'rildi"), ('answered', 'Javob berildi'), ('pending', 'Kutilmoqda'), ('closed', 'Yopilgan')], default='new', max_length=10, verbose_name='Xabar holati')),
                ('response_content', models.TextField(blank=True, null=True, verbose_name="Javob (mas'ul shaxsdan)")),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Javob berilgan vaqti')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Oxirgi yangilanish')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_messages', to=settings.AUTH_USER_MODEL, verbose_name='Javob bergan shaxs')),
                ('responsible_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_messages_from_students', to='auth_app.responsibleperson', verbose_name="Qabul qiluvchi mas'ul shaxs")),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages_to_responsible', to='auth_app.student', verbose_name='Yuboruvchi talaba')),
            ],
            options={
                'verbose_name': "Mas'ul shaxsga xabar",
                'verbose_name_plural': "Mas'ul shaxslarga xabarlar",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Ruxsat etilgan formatlar: PDF, DOC, DOCX, XLS, XLSX, JPG, JPEG, PNG, MP3, WAV, OGG, MP4, MOV, AVI.', upload_to=auth_app.models.message_attachment_upload_path, verbose_name='Biriktirilgan fayl')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='Asl fayl nomi (avtomatik)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='auth_app.messagetoresponsible', verbose_name='Xabar')),
            ],
            options={
                'verbose_name': 'Xabarga biriktirma',
                'verbose_name_plural': 'Xabarga biriktirmalar',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Variant matni')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='auth_app.question', verbose_name='Savol')),
            ],
            options={
                'verbose_name': 'Tanlov varianti',
                'verbose_name_plural': 'Tanlov variantlari',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, null=True, verbose_name='Matnli javob')),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='auth_app.question', verbose_name='Savol')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chosen_in_answers', to='auth_app.choice', verbose_name='Tanlangan yagona variant')),
                ('selected_choices', models.ManyToManyField(blank=True, related_name='multi_chosen_in_answers', to='auth_app.choice', verbose_name="Tanlangan ko'p variantlar")),
                ('survey_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='auth_app.surveyresponse', verbose_name="So'rovnoma ishtiroki")),
            ],
            options={
                'verbose_name': 'Javob',
                'verbose_name_plural': 'Javoblar',
                'ordering': ['survey_response', 'question__order'],
                'unique_together': {('survey_response', 'question')},
            },
        ),
    ]
