# Generated by Django 4.2.20 on 2025-05-29 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_responsibleperson_survey_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to='auth_app.student', verbose_name='Talaba'),
        ),
    ]
