# Generated by Django 4.2.20 on 2025-06-13 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_alter_surveyresponse_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='selected_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chosen_in_answers', to='auth_app.choice'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text_answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
