# Generated by Django 4.2.20 on 2025-06-13 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_alter_answer_question_alter_answer_selected_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='selected_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chosen_in_answers', to='auth_app.choice', verbose_name='Tanlangan yagona variant'),
        ),
    ]
