# Generated by Django 4.2.20 on 2025-06-20 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_app', '0008_alter_student_accommodation_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetoresponsible',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='message_qrcodes/', verbose_name='QR kod rasmi'),
        ),
        migrations.AddField(
            model_name='messagetoresponsible',
            name='unique_code',
            field=models.CharField(default=1, editable=False, max_length=6, unique=True, verbose_name='Murojaat ID (6 xonali)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='responsibleperson',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Surat (URL)'),
        ),
        migrations.AddField(
            model_name='responsibleperson',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram username'),
        ),
        migrations.CreateModel(
            name='MessageReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Javob matni')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Javob vaqti')),
                ('unique_code', models.CharField(editable=False, max_length=8, unique=True, verbose_name='Javob ID (8 xonali)')),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='message_qrcodes/replies/', verbose_name='QR kod (javob)')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='auth_app.messagetoresponsible', verbose_name='Xabar')),
                ('replied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Javob bergan shaxs')),
            ],
            options={
                'verbose_name': 'Xabar javobi',
                'verbose_name_plural': 'Xabar javoblari',
                'ordering': ['-created_at'],
            },
        ),
    ]
